server:
  port: 9868
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/test_dev}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    druid:
      max-active: 100
      min-idle: 5
      initial-size: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        slf4j:
          statement-sql-pretty-format: true
          result-set-log-enabled: false
          statement-executable-sql-log-enable: false
          enabled: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      test-while-idle: true


#mybaits
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.github.szl.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
